### ISSUE TITLE
the truth value of an array with more than one element is

### ISSUE THREAD

**Issue by susanhc** [zheng-yuwei/YOLOv2-tensorflow#2]
![TIM截图20191224203251](https://user-images.githubusercontent.com/40540203/71413333-aee8f100-268c-11ea-9e31-4614b9fba55e.jpg)
I have meet the error above,so I want to know the version of keras you use.

**Comment by zheng-yuwei** [comment]
TensorFlow version: 1.13.1
tf.keras version: 2.2.4-tf

I think if you run with the right version of tensorflow, the tf.keras version would be right too.

**Comment by susanhc** [comment]
ok ,i will updata the version .thanks so much.

**Comment by zheng-yuwei** [comment]
by the way, you can check the version in `requirements.txt` in the project.
