### ISSUE TITLE
关于tf.data的padded_batch使用问题

### ISSUE THREAD

**Issue by YongshengDong** [zheng-yuwei/YOLOv2-tensorflow#3]
https://github.com/zheng-yuwei/YOLOv2-tensorflow/blob/832c2e9e17620b46eca6b53843269a32592dc74e/dataset/file_util.py#L97

hi，请教一个问题，在读取数据的时候，针对objs不定长问题用了padding，但是在处理数据的时候如何操作呢？逐个batch拆分开处理吗？您的代码中相关操作的位置在哪里呢？谢谢

**Comment by zheng-yuwei** [comment]
https://github.com/zheng-yuwei/YOLOv2-tensorflow/blob/832c2e9e17620b46eca6b53843269a32592dc74e/yolov2/yolov2_loss.py#L157

这一个方法里负责取出有效的gt，当然，前面已经做了一步标签解码的，整个流程可以参考整个loss函数，步骤注释很清楚

https://github.com/zheng-yuwei/YOLOv2-tensorflow/blob/832c2e9e17620b46eca6b53843269a32592dc74e/yolov2/yolov2_loss.py#L71

**Comment by zheng-yuwei** [comment]
这方面有什么问题可以再reopen~
